### ISSUE TITLE
[AVM Module Issue]: User Assigned Managed Identity module not being passed the tags - Inconsistent tags on resources

### ISSUE THREAD

**Issue by LeighS** [Azure/terraform-azurerm-avm-ptn-cicd-agents-and-runners#73]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

0.1.3

### Description

When deploying the solution, the tags are assigned on most resources but not the User Assigned Managed Identity. 

This is a pain if you have policy that applies tags automatically as the terraform will always try and remove the tags from this resource every deployment.

![Image](https://github.com/user-attachments/assets/14febebf-35ba-471e-a2af-4e0010cba617)

**Comment by AErmie** [comment]
The issue with the module removing tags seems to affect all resource types:

![Image](https://github.com/user-attachments/assets/38bb3b92-466e-4cf1-a9f1-babbeb35f872)

**Comment by jaredfholgate** [comment]
> The issue with the module removing tags seems to affect all resource types:
> 
> ![Image](https://github.com/user-attachments/assets/38bb3b92-466e-4cf1-a9f1-babbeb35f872)

Hi

This is not an AVM module (or this module) specific problem. If you are using policy to manage tags and you are deploying resources with IaC you will hit these idempotency issues.

Terraform does not know about your tags since it didn't created them. Therefore it plans to destroy the.

We are working towards a solution for this particular issue with AVM modules. You can see an example here in this pull request of the standard interface we are considering: https://github.com/Azure/terraform-azurerm-avm-res-network-virtualnetwork/pull/119. This will allow Terraform to merge tags from the subscription and / or resource group via single setting.

In the meantime, you'll either need to:

- Supply the tags via Terraform (read from your resource group or subscription and supply them to the tags variable)
- Accept that they will be destroyed and then re-created by policy
- Stop apply tags by policy for resources managed by Terraform.

Unfortunately Terraform modules do not support the lifecycle block, so there is no other work around.
